name: API Generate Action
on: [push, pull_request]
jobs:
  API-Generate-Action:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: nikeee/docfx-action@master
      name: Build Documentation
      with:
        args: docfx.json
    - uses: maxheld83/ghpages@master
      name: Publish Documentation on GitHub Pages
      env:
        BUILD_DIR: public/
        GH_PAT: ${{ secrets.GH_PAT }} # See https://github.com/maxheld83/ghpages
      