name: API Generate Action
on: [push]
jobs:
  API-Generate-Action:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: nikeee/docfx-action@master
      name: Build Documentation
      with:
        args: docfx_project\docfx.json
      