name: API Generate Action
on: [push]
jobs:
  API-Generate-Action:
    runs-on: ubuntu-latest
    steps:
      - name: coco/docfx-action@master
        uses: nikeee/docfx-action@v1.0.0
        with:
          args: docfx_project/docfx.json
      