name: API Generate Action
on: [push, pull_request]
jobs:
  API-Generate-Action:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: nikeee/docfx-action@master
      name: Build Documentation
      with:
        args: docfx.json
    - uses: maxheld83/ghpages@master
      name: Publish Documentation on GitHub Pages
      env:
        BUILD_DIR: _site # docfx's default output directory is _site
        GH_PAT: ${{ secrets.GH_PAT }} # See https://github.com/maxheld83/ghpages
  deploy_ghpages:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - run: echo $GITHUB_SHA >> public/index.html
      - uses: maxheld83/ghpages@v0.3.0
        env:
          BUILD_DIR: public/
          GH_PAT: ${{ secrets.GH_PAT }}
      